### ISSUE TITLE
reset timer

### ISSUE THREAD

**Issue by msadeghyan1996** [noorzaie/vue-circular-count-down-timer#4]
Hello. tanx for this package it's perfect and awesome.
how can i reset timer and set new second?
i count down 59 to 0 and when == 0 i want reset timer to 59.

**Comment by noorzaie** [comment]
Hi @msadeghyan1996. You should pass a variable to the `initial-value` prop and set it to proper value in your `@update` event listener.

**Comment by msadeghyan1996** [comment]
tanks @noorzaie but if i want reset timer with Button i need a stop and start function.
i want if timer == 0 show a reset button for user and when user click on reset button timer set ti 59 and restart count down to 0.
can i do it whit @update function?

**Comment by noorzaie** [comment]
You should set a variable to `true` in the `@update` function to show the reset button, and then set `initial-value` prop to 59 in the button click event listener.

**Comment by KLala94** [comment]
it would be nice to update it with the updateTime() method.
can you provide the code how i can update it when the timer is set to zero?.
so that everybody will save time when searching for it.
Thanks in advance
from a Vue lover

**Comment by KLala94** [comment]
my solution was to:
```javascript
updateCountdown: function(sec) {
      this.$refs.countdown.updateTime(sec);
    },
    finished: function() {
      // this.seconds = 0;
    },
    updated: function(status) {
      if (status.seconds === 1) {
        return (this.pause = true);
      } else {
        return (this.pause = false);
      }
    }
```

**Comment by maxirby** [comment]
> my solution was to:
> 
> ```js
> updateCountdown: function(sec) {
>       this.$refs.countdown.updateTime(sec);
>     },
>     finished: function() {
>       // this.seconds = 0;
>     },
>     updated: function(status) {
>       if (status.seconds === 1) {
>         return (this.pause = true);
>       } else {
>         return (this.pause = false);
>       }
>     }
> ```
So, count-down will never reach 0.
Is it possible to reach 0 and restart count-down?

**Comment by HaiseCoffee** [comment]
it always says 

> > my solution was to:
> > ```js
> > updateCountdown: function(sec) {
> >       this.$refs.countdown.updateTime(sec);
> >     },
> >     finished: function() {
> >       // this.seconds = 0;
> >     },
> >     updated: function(status) {
> >       if (status.seconds === 1) {
> >         return (this.pause = true);
> >       } else {
> >         return (this.pause = false);
> >       }
> >     }
> > ```
> 
> So, count-down will never reach 0.
> Is it possible to reach 0 and restart count-down?

it always says updateTime is undefined
